# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
   schedule:
    - cron:  '*/1 * * * *'    

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run Test
        run: echo TEST CRON
